name: mxflutter
description: JavaScript Flutter Framework,Using mxflutter lib, you can use JavaScript to develop flutter or use Dart to develop and compile to JS.
version: 0.2.1
homepage: https://github.com/mxflutter/mxflutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # MXFlutter Framework 必须的库
  vector_math: ^2.0.8
  expressions: ^0.1.2

  # 开发者选用的库
  dio: ^3.0.9
  pull_to_refresh: ^1.5.7
  cached_network_image: ^2.0.0-rc.1
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #mxflutter_js_framework
    - js_lib/
    - js_lib/framework/
    - js_lib/framework/material/
    - js_lib/framework/message_channel/
    - js_lib/framework/widgets/

    #dart_js_framework
    - js_lib/framework/dart_js_framework/

    #packages js ,按需选择
    - js_lib/framework/mx_packages/

    #cached_network_image
    - js_lib/framework/mx_packages/cached_network_image/
    #dio
    - js_lib/framework/mx_packages/dio/
    - js_lib/framework/mx_packages/dio/src/
    - js_lib/framework/mx_packages/dio/src/adapters/
    - js_lib/framework/mx_packages/dio/src/entry/
    #pull_to_refresh
    - js_lib/framework/mx_packages/pull_to_refresh/
    - js_lib/framework/mx_packages/pull_to_refresh/src/
    - js_lib/framework/mx_packages/pull_to_refresh/src/indicator/
    #shared_preferences
    - js_lib/framework/mx_packages/shared_preferences/

  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.mojitox.mxflutter
    pluginClass: MXFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages



